name: Metrics
on:
  # Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: MBTI Personality profile
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.plugin.16personalities.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_16personalities: yes
          plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
          plugin_16personalities_sections: personality, profile, traits
          plugin_16personalities_scores: yes
